# Generated by Django 4.2.1 on 2023-05-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_converted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='middle_name',
            field=models.CharField(default='Отчество', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='Отчество', max_length=20),
            preserve_default=False,
        ),
    ]
