# Generated by Django 4.2.1 on 2023-05-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_agent_profile_picture_alter_lead_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
