# Generated by Django 4.2.1 on 2023-06-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_lead_address_alter_lead_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.CharField(choices=[('YOUNG', 'Молодой'), ('MIDDLE', 'Средний'), ('OLD', 'Пожилой')], default='Не указан', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='order',
            field=models.CharField(max_length=255),
        ),
    ]
