# Generated by Django 4.2.1 on 2023-06-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_lead_address_alter_lead_age_alter_lead_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.CharField(choices=[('Не указан', 'Не указан'), ('Молодой', 'Молодой'), ('Средний', 'Средний'), ('Пожилой', 'Пожилой')], default=('Не указан', 'Не указан'), max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-profile-pic.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
