# Generated by Django 4.2.1 on 2023-06-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_remove_test_order_testorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorders',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.order'),
        ),
        migrations.AlterField(
            model_name='testorders',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.test'),
        ),
    ]
