# Generated by Django 4.2.1 on 2023-06-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_alter_testorders_order_alter_testorders_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.test'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.category'),
        ),
        migrations.DeleteModel(
            name='TestOrders',
        ),
    ]
