# Generated by Django 4.2.1 on 2023-06-25 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_order_test_alter_order_category_delete_testorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='test',
            new_name='client',
        ),
    ]
