# Generated by Django 4.2.1 on 2023-06-26 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_rename_test_client_rename_test_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
