# Generated by Django 4.2.1 on 2023-06-26 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_remove_lead_order_remove_order_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
    ]
