# Generated by Django 4.2.1 on 2023-06-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_remove_order_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='converted_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
